import { NextRequest, NextResponse } from "next/server";
import { checkRateLimit } from "@/lib/rate-limiter";

const SYSTEM_PROMPT = `You are an expert AI content detection analyst. Your task is to analyze text and determine whether it was written by a human or generated by an AI language model (ChatGPT, Claude, Gemini, etc).

Analyze the provided text across these 5 detection signals, scoring each 0-100 (0 = definitely human, 100 = definitely AI):

1. **Perplexity & Predictability**: How predictable is the word choice? AI text tends to use the most statistically likely next word, creating low-perplexity text. Human writing is more surprising and varied. Look for: overly smooth flow, lack of unexpected word choices, predictable sentence transitions.

2. **Burstiness & Rhythm**: Human writing varies sentence length dramatically — short punchy sentences mixed with long complex ones. AI tends to produce more uniform sentence lengths and paragraph structures. Look for: consistent sentence length, uniform paragraph structure, lack of rhythm variation.

3. **Vocabulary & Phrasing**: AI models favor certain phrases and vocabulary patterns. Look for: overuse of words like "delve", "crucial", "furthermore", "landscape", "leverage", "streamline", "robust", "comprehensive", "facilitate", "in today's [X]", "it's important to note", "in conclusion". Also check for unnaturally formal or consistently neutral tone.

4. **Structural Patterns**: AI text often follows predictable structures — introduction, enumerated points, balanced paragraphs, tidy conclusions. Human writing is messier, more organic, with tangents and asymmetric structure. Look for: formulaic organization, balanced paragraph lengths, predictable topic sentences, neat summarization.

5. **Authenticity Markers**: Human writing contains personal voice markers — colloquialisms, contractions, emotional inconsistency, self-correction, specificity of experience, cultural references, humor, opinions stated as opinions rather than facts. AI text tends to be more neutral, hedging, and generically authoritative. Look for: absence of personal voice, excessive hedging, generic examples, lack of specificity.

For each signal provide:
- A score from 0 (definitely human) to 100 (definitely AI)
- A verdict: "human" (0-20), "likely_human" (21-40), "mixed" (41-60), "likely_ai" (61-80), "ai" (81-100)
- A description of what this signal measures (1 sentence)
- 2-4 specific findings from the text
- An explanation of why this matters (1-2 sentences)

Also analyze EACH SENTENCE individually. For every sentence in the text, provide:
- The exact sentence text (must match the original input exactly)
- AI probability (0-100)
- Verdict (human/likely_human/mixed/likely_ai/ai)
- 1-2 brief signal notes (e.g. "predictable phrasing", "natural voice", "AI vocabulary marker: 'delve'")

Calculate an overall AI probability score (0-100) as an equally weighted average of the 5 signals.

Also calculate a confidence score (0-100) reflecting how confident you are in the overall verdict. Short texts, technical writing, and formal business communication should have LOWER confidence since these naturally resemble AI output.

Provide an educational note (2-3 sentences) teaching the user what specific patterns in THIS text suggest human or AI origin. This should be genuinely educational, not just restating the score.

Calculate these text statistics:
- Word count
- Sentence count
- Average words per sentence
- Vocabulary richness (unique words / total words, as percentage)
- Average sentence length (same as avg words per sentence)
- Longest sentence (word count)
- Shortest sentence (word count)

Respond ONLY with valid JSON matching this structure (no markdown, no backticks):
{
  "overallScore": <number 0-100>,
  "overallVerdict": "<human|likely_human|mixed|likely_ai|ai>",
  "verdictText": "<one sentence summary>",
  "confidence": <number 0-100>,
  "signals": [
    {
      "name": "<signal name>",
      "score": <number 0-100>,
      "verdict": "<verdict>",
      "description": "<what this signal measures>",
      "findings": ["<finding 1>", "<finding 2>"],
      "explanation": "<why this matters>"
    }
  ],
  "sentenceAnalysis": [
    {
      "text": "<exact sentence>",
      "aiProbability": <number 0-100>,
      "verdict": "<verdict>",
      "signals": ["<signal note 1>", "<signal note 2>"]
    }
  ],
  "stats": {
    "wordCount": <number>,
    "sentenceCount": <number>,
    "avgWordsPerSentence": <number>,
    "vocabularyRichness": <number>,
    "avgSentenceLength": <number>,
    "longestSentence": <number>,
    "shortestSentence": <number>
  },
  "summary": "<2-3 sentence analysis summary>",
  "educationalNote": "<2-3 sentences teaching what patterns indicate human vs AI in this specific text>"
}

Important guidelines:
- Be calibrated. Not all formal text is AI. Not all casual text is human.
- Academic papers, legal documents, and technical writing naturally score higher on some AI signals — adjust confidence accordingly.
- Short texts (under 100 words) should have lower confidence.
- Focus on PATTERNS across the text, not individual words.
- The sentence-level analysis should be honest — most texts have a mix of AI-like and human-like sentences.
- The sentence text MUST match the original input exactly so the client can highlight it.`;

export async function POST(request: NextRequest) {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: "Service temporarily unavailable. Please try again later." },
      { status: 503 }
    );
  }

  let body: { content?: string };
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  const content = body.content?.trim() ?? "";

  if (content.length < 50) {
    return NextResponse.json(
      { error: "Please paste at least 50 characters (a few sentences) for accurate detection." },
      { status: 400 }
    );
  }

  if (content.length > 10_000) {
    return NextResponse.json(
      { error: "Please limit text to 10,000 characters." },
      { status: 400 }
    );
  }

  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    request.headers.get("x-real-ip") ||
    "unknown";

  const { allowed } = checkRateLimit(ip, 5, 60 * 60 * 1000);
  if (!allowed) {
    return NextResponse.json(
      { error: "Rate limit reached. You can analyze up to 5 texts per hour. Please try again later." },
      { status: 429 }
    );
  }

  try {
    const aiResponse = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        temperature: 0.3,
        max_tokens: 4000,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content },
        ],
      }),
    });

    if (!aiResponse.ok) {
      const errText = await aiResponse.text();
      console.error("OpenAI API error:", errText);
      return NextResponse.json(
        { error: "Analysis failed. Please try again." },
        { status: 502 }
      );
    }

    const data = await aiResponse.json();
    let analysisJson = data.choices?.[0]?.message?.content ?? "";

    // Strip markdown backticks if present
    analysisJson = analysisJson
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/\s*```$/i, "")
      .trim();

    const analysis = {
      ...JSON.parse(analysisJson),
      analyzedAt: new Date().toISOString(),
    };

    return NextResponse.json(analysis);
  } catch (err) {
    console.error("Detection analysis error:", err);
    return NextResponse.json(
      { error: "Something went wrong. Please try again." },
      { status: 500 }
    );
  }
}
